import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Job from '../src/models/Job.js';

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/resume-analyzer';

const sampleJobs = [
  {
    title: 'Senior Frontend Engineer',
    company: 'TechCorp',
    description: 'We are looking for an experienced frontend engineer to lead our React team and build beautiful, accessible user interfaces.',
    location: 'San Francisco, CA',
    workModel: 'hybrid',
    type: 'full-time',
    level: 'senior',
    requiredSkills: ['JavaScript', 'React', 'TypeScript', 'CSS', 'HTML5', 'Git'],
    niceToHaveSkills: ['Next.js', 'GraphQL', 'AWS', 'Jest'],
    salaryRange: { min: 140000, max: 180000, currency: 'USD' },
    url: 'https://example.com/jobs/techcorp-frontend',
  },
  {
    title: 'Backend Developer (Node.js)',
    company: 'InnovateIO',
    description: 'Join our scalable backend team building microservices with Node.js, Express, and MongoDB.',
    location: 'New York, NY',
    workModel: 'remote',
    type: 'full-time',
    level: 'mid',
    requiredSkills: ['Node.js', 'Express', 'JavaScript', 'MongoDB', 'REST APIs'],
    niceToHaveSkills: ['Docker', 'Kubernetes', 'Redis', 'AWS'],
    salaryRange: { min: 110000, max: 140000, currency: 'USD' },
    url: 'https://example.com/jobs/innovateio-backend',
  },
  {
    title: 'Full Stack Web Developer',
    company: 'StartupX',
    description: 'Fast-paced startup looking for a full stack developer comfortable with the MERN stack.',
    location: 'Austin, TX',
    workModel: 'remote',
    type: 'full-time',
    level: 'mid',
    requiredSkills: ['MongoDB', 'Express.js', 'React', 'Node.js', 'JavaScript'],
    niceToHaveSkills: ['TypeScript', 'Tailwind CSS', 'PostgreSQL'],
    salaryRange: { min: 100000, max: 130000, currency: 'USD' },
    url: 'https://example.com/jobs/startupx-fullstack',
  },
  {
    title: 'Junior React Developer',
    company: 'WebSolutions',
    description: 'Great entry-level opportunity for a passionate React developer eager to learn and grow.',
    location: 'Chicago, IL',
    workModel: 'on-site',
    type: 'full-time',
    level: 'junior',
    requiredSkills: ['JavaScript', 'React', 'HTML', 'CSS'],
    niceToHaveSkills: ['Redux', 'Git', 'Figma'],
    salaryRange: { min: 70000, max: 90000, currency: 'USD' },
    url: 'https://example.com/jobs/websolutions-junior',
  },
  {
    title: 'DevOps Engineer',
    company: 'CloudScale',
    description: 'We need a DevOps engineer to manage our CI/CD pipelines and Kubernetes clusters.',
    location: 'Seattle, WA',
    workModel: 'hybrid',
    type: 'full-time',
    level: 'senior',
    requiredSkills: ['Linux', 'Docker', 'Kubernetes', 'CI/CD', 'AWS', 'Terraform'],
    niceToHaveSkills: ['Python', 'Bash', 'Prometheus', 'Grafana'],
    salaryRange: { min: 150000, max: 190000, currency: 'USD' },
    url: 'https://example.com/jobs/cloudscale-devops',
  },
  {
    title: 'Data Scientist',
    company: 'DataMinds',
    description: 'Looking for a data scientist to build machine learning models for predictive analytics.',
    location: 'Boston, MA',
    workModel: 'remote',
    type: 'full-time',
    level: 'mid',
    requiredSkills: ['Python', 'SQL', 'Machine Learning', 'Pandas', 'Scikit-Learn'],
    niceToHaveSkills: ['TensorFlow', 'PyTorch', 'AWS', 'Data Visualization'],
    salaryRange: { min: 120000, max: 160000, currency: 'USD' },
    url: 'https://example.com/jobs/dataminds-ds',
  },
  {
    title: 'Mobile App Developer (React Native)',
    company: 'AppWorks',
    description: 'Build cross-platform mobile apps using React Native and modern JavaScript.',
    location: 'Denver, CO',
    workModel: 'remote',
    type: 'contract',
    level: 'mid',
    requiredSkills: ['JavaScript', 'React Native', 'Mobile Development', 'REST APIs'],
    niceToHaveSkills: ['TypeScript', 'Swift', 'Kotlin', 'Firebase'],
    salaryRange: { min: 90000, max: 120000, currency: 'USD' },
    url: 'https://example.com/jobs/appworks-mobile',
  },
  {
    title: 'UI/UX Designer',
    company: 'CreativeAgency',
    description: 'Design intuitive and beautiful user interfaces for our diverse client portfolio.',
    location: 'Los Angeles, CA',
    workModel: 'hybrid',
    type: 'full-time',
    level: 'mid',
    requiredSkills: ['Figma', 'UI Design', 'UX Research', 'Prototyping', 'Wireframing'],
    niceToHaveSkills: ['HTML', 'CSS', 'Adobe Creative Suite'],
    salaryRange: { min: 95000, max: 125000, currency: 'USD' },
    url: 'https://example.com/jobs/creative-uiux',
  },
  {
    title: 'Product Manager',
    company: 'VisionaryTech',
    description: 'Lead product development from conception to launch, working closely with engineering and design.',
    location: 'San Francisco, CA',
    workModel: 'hybrid',
    type: 'full-time',
    level: 'senior',
    requiredSkills: ['Product Management', 'Agile', 'Scrum', 'Data Analysis', 'Roadmapping'],
    niceToHaveSkills: ['Jira', 'SQL', 'A/B Testing'],
    salaryRange: { min: 130000, max: 170000, currency: 'USD' },
    url: 'https://example.com/jobs/visionary-pm',
  },
  {
    title: 'Security Analyst',
    company: 'SecureNet',
    description: 'Monitor our networks for security breaches and investigate violations when they occur.',
    location: 'Washington, D.C.',
    workModel: 'on-site',
    type: 'full-time',
    level: 'mid',
    requiredSkills: ['Cybersecurity', 'Network Security', 'Incident Response', 'Linux'],
    niceToHaveSkills: ['CEH', 'CISSP', 'Python scripting'],
    salaryRange: { min: 105000, max: 135000, currency: 'USD' },
    url: 'https://example.com/jobs/securenet-analyst',
  },
  {
    title: 'Staff Software Engineer',
    company: 'GlobalCorp',
    description: 'Architect technical solutions and mentor engineers across multiple product teams.',
    location: 'Remote',
    workModel: 'remote',
    type: 'full-time',
    level: 'staff',
    requiredSkills: ['System Architecture', 'Java', 'Spring Boot', 'Microservices', 'Distributed Systems'],
    niceToHaveSkills: ['Kafka', 'Cassandra', 'AWS', 'Kubernetes'],
    salaryRange: { min: 180000, max: 240000, currency: 'USD' },
    url: 'https://example.com/jobs/globalcorp-staff',
  },
  {
    title: 'Quality Assurance Tester',
    company: 'QAPro',
    description: 'Ensure our software meets quality standards through manual and automated testing.',
    location: 'Atlanta, GA',
    workModel: 'hybrid',
    type: 'full-time',
    level: 'junior',
    requiredSkills: ['Manual Testing', 'Test Cases', 'Jira', 'Bug Tracking'],
    niceToHaveSkills: ['Selenium', 'Cypress', 'JavaScript'],
    salaryRange: { min: 65000, max: 85000, currency: 'USD' },
    url: 'https://example.com/jobs/qapro-tester',
  },
  {
    title: 'Data Engineer',
    company: 'DataStream',
    description: 'Design, build, and optimize data pipelines for our analytics infrastructure.',
    location: 'Seattle, WA',
    workModel: 'remote',
    type: 'full-time',
    level: 'senior',
    requiredSkills: ['Python', 'SQL', 'Spark', 'ETL', 'AWS', 'Data Warehousing'],
    niceToHaveSkills: ['Airflow', 'Snowflake', 'Scala', 'Hadoop'],
    salaryRange: { min: 140000, max: 175000, currency: 'USD' },
    url: 'https://example.com/jobs/datastream-de',
  },
  {
    title: 'Technical Writer',
    company: 'DocuTech',
    description: 'Create clear, concise documentation for our developer APIs and SDKs.',
    location: 'Austin, TX',
    workModel: 'remote',
    type: 'full-time',
    level: 'mid',
    requiredSkills: ['Technical Writing', 'Markdown', 'API Documentation', 'Git'],
    niceToHaveSkills: ['JavaScript', 'Python', 'OpenAPI/Swagger'],
    salaryRange: { min: 80000, max: 110000, currency: 'USD' },
    url: 'https://example.com/jobs/docutech-writer',
  },
  {
    title: 'Site Reliability Engineer',
    company: 'AlwaysOn',
    description: 'Ensure our services remain highly available, scalable, and performant.',
    location: 'New York, NY',
    workModel: 'hybrid',
    type: 'full-time',
    level: 'senior',
    requiredSkills: ['Linux', 'Go', 'Python', 'Kubernetes', 'Monitoring', 'Terraform'],
    niceToHaveSkills: ['Datadog', 'Incident Management', 'AWS'],
    salaryRange: { min: 150000, max: 190000, currency: 'USD' },
    url: 'https://example.com/jobs/alwayson-sre',
  },
  {
    title: 'Frontend Intern',
    company: 'StartupX',
    description: 'Join us for a summer internship to learn frontend web development.',
    location: 'Austin, TX',
    workModel: 'on-site',
    type: 'internship',
    level: 'junior',
    requiredSkills: ['HTML', 'CSS', 'JavaScript basic'],
    niceToHaveSkills: ['React', 'Git'],
    salaryRange: { min: 40000, max: 50000, currency: 'USD' },
    url: 'https://example.com/jobs/startupx-intern',
  },
  {
    title: 'Cloud Architect',
    company: 'EnterpriseCloud',
    description: 'Design and implement enterprise cloud solutions on AWS and Azure.',
    location: 'Chicago, IL',
    workModel: 'remote',
    type: 'full-time',
    level: 'lead',
    requiredSkills: ['AWS', 'Azure', 'Cloud Architecture', 'Infrastructure as Code', 'Networking'],
    niceToHaveSkills: ['GCP', 'Kubernetes', 'Security Compliance'],
    salaryRange: { min: 170000, max: 220000, currency: 'USD' },
    url: 'https://example.com/jobs/enterprise-cloud',
  },
  {
    title: 'Machine Learning Engineer',
    company: 'AI Forward',
    description: 'Deploy and optimize machine learning models in production environments.',
    location: 'San Francisco, CA',
    workModel: 'hybrid',
    type: 'full-time',
    level: 'senior',
    requiredSkills: ['Python', 'Machine Learning', 'TensorFlow', 'PyTorch', 'Model Deployment', 'Docker'],
    niceToHaveSkills: ['MLOps', 'Kubernetes', 'C++'],
    salaryRange: { min: 160000, max: 210000, currency: 'USD' },
    url: 'https://example.com/jobs/aiforward-mle',
  },
  {
    title: 'Sales Engineer',
    company: 'B2B Solutions',
    description: 'Bridge the gap between our technical product and enterprise clients.',
    location: 'Remote',
    workModel: 'remote',
    type: 'full-time',
    level: 'mid',
    requiredSkills: ['Technical Sales', 'Communication', 'Presentations', 'API Knowledge', 'Problem Solving'],
    niceToHaveSkills: ['CRM software', 'JavaScript', 'SQL'],
    salaryRange: { min: 110000, max: 150000, currency: 'USD' },
    url: 'https://example.com/jobs/b2b-se',
  },
  {
    title: 'Game Developer (Unity)',
    company: 'PlayStudios',
    description: 'Create engaging mobile and PC games using Unity and C#.',
    location: 'Los Angeles, CA',
    workModel: 'on-site',
    type: 'full-time',
    level: 'mid',
    requiredSkills: ['Unity', 'C#', 'Game Design', '3D Math'],
    niceToHaveSkills: ['Unreal Engine', 'C++', 'Shaders'],
    salaryRange: { min: 90000, max: 130000, currency: 'USD' },
    url: 'https://example.com/jobs/playstudios-dev',
  }
];

async function seedJobs() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI);
    console.log('Connected.');

    console.log('Clearing existing jobs...');
    await Job.deleteMany({});

    console.log(`Seeding ${sampleJobs.length} sample jobs...`);
    await Job.insertMany(sampleJobs);

    console.log('Job seeding complete!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding jobs:', error);
    process.exit(1);
  }
}

seedJobs();
